### ISSUE TITLE
[Bug]: Stationeers dedicated server has been overhauled and the egg no longer functions.

### ISSUE THREAD

**Issue by Butain** [parkervcp/eggs#1752]
### Panel Version

1.2.2

### Wings Version

1.2.3

### Service

stationeers

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server, configure settings, start server.

log of the console:

https://pastebin.com/3wKNNZMS

### Actual Behavior

Server hangs with errors

log of the console:
https://pastebin.com/3wKNNZMS

### Steps To Reproduce

Install stationeers server on panel, modify settings for the world and map, and attempt to start the server.
Stationeer developers provided github with instructions on how the new functionality works.

https://github.com/rocket2guns/StationeersDedicatedServerGuide/blob/main/README.md

### Install logs

https://pteropaste.com/3f152z

**Comment by QuintenQVD0** [comment]
The install looks fine but you run a very old panel and wings version.

**Comment by gOOvER** [comment]
Update your panel first; you are using a fucking old version

**Comment by Butain** [comment]
I updated to php 8.1, composer v2, wings 1.6.4, and panel 1.9.2
reinstalled the server, tried again fresh.
This has made no difference, still get the same error.
https://pastebin.com/XeP1rFVt

**Comment by gOOvER** [comment]
Stationeers Team rewrote the whole server and the egg needs to be updated to work again. Alone the startup is complete dfferent.

**Comment by gOOvER** [comment]
As log they fixed not their console, stationeers only work with a ugly workaround

**Comment by tiweb442** [comment]
> As log they fixed not their console, stationeers only work with a ugly workaround
> 
> as workaround; add "previous" to beta and use the old server and client

can you post your egg ?

**Comment by tiweb442** [comment]
also not working for me have the same prob from the first post

**Comment by gOOvER** [comment]
> also not working for me have the same prob from the first post

did you read what i wrote?

**Comment by Neouni** [comment]
"docker -it" should fix it, it will complain if there is no console attached at all times.
I hope they redesign it.

**Comment by gOOvER** [comment]
> "docker -it" should fix it, it will complain if there is no console attached at all times. I hope they redesign it.

as i see, ptero use -it flag.

**Comment by Erani0** [comment]
any news for a update the egg

**Comment by Sakata-MC** [comment]
Is there any updates for this? I'm still not able to get Stationeers server to start, and the last update to the egg was over 9 months ago.

**Comment by gOOvER** [comment]
Please test this. I rewrote the full egg, becasue the installscript was complete wrong:

https://github.com/gOOvER/parkervcp-eggs/tree/serewrite/game_eggs/steamcmd_servers/space_engineers

**Comment by Software-Noob** [comment]
> Please test this. I rewrote the full egg, becasue the installscript was complete wrong:
> 
> [gOOvER/parkervcp-eggs@`serewrite`/game_eggs/steamcmd_servers/space_engineers](https://github.com/gOOvER/parkervcp-eggs/tree/serewrite/game_eggs/steamcmd_servers/space_engineers?rgh-link-date=2022-11-05T05%3A44%3A31Z)

Space Engineers and stationeers are two different games?

**Comment by gOOvER** [comment]
> > Please test this. I rewrote the full egg, becasue the installscript was complete wrong:
> > [gOOvER/parkervcp-eggs@`serewrite`/game_eggs/steamcmd_servers/space_engineers](https://github.com/gOOvER/parkervcp-eggs/tree/serewrite/game_eggs/steamcmd_servers/space_engineers?rgh-link-date=2022-11-06T13%3A35%3A16Z)
> 
> Space Engineers and stationeers are two different games?

yeah, my fail; clicked the wrong ticket
