### ISSUE TITLE
 Wont read log file.

### ISSUE THREAD

**Issue by AndersNorman** [parkervcp/eggs#31]
Please fill out the information bellow and remove from the line up
---------------
Panel Version: 0.7.6
Daemon Version: unknown. 
New Service:no
Service: 7 days to die
Modified: Yes

Expected Behavior: To read the log file and output it in the console window

Actual Behavior: Wont read the log file.

Steps to Reproduce: Start the server... Thats it. the outlog file is there but the server refuses to read it.

Egg can be found here. 

https://github.com/pterodactyl/panel/files/1868067/egg-7-days-to-die.zip

**Comment by Daxorinator** [comment]
Again, nothing to do with reading log files, what's happening here is:

This guy is setting up 7 Days to Die, which is running fine, everything's perfect.
Except, the gameserver isn't sending it's output to the Pterodactyl console, which means on the panel you see nothing apart from the usual Docker starting up stuff.
However, if you look at the log files for the game, which are defined in the egg settings, they show everything you'd expect to see in the console. The log file itself is full with the stuff we need, it's just not being displayed for some reason. It should be noted that commands aren't being sent to the server either.

The same thing was happening with SA:MP, it wouldn't even output the one-liner "server is started" thing it usually does. Apparently it was fixed though and works now.

**Comment by AndersNorman** [comment]
The 7 days to die server isn't fixed so you guys dont mistaken SA:MP for 7 days to die.

**Comment by AndersNorman** [comment]
Any updates?

**Comment by parkervcp** [comment]
I got this working. But now I am working on actually being able to stop the server properly...

**Comment by Daxorinator** [comment]
Oh wow, I never thought this would get fixed tbh I thought it was a game
issue. Nice work.

**Comment by parkervcp** [comment]
It is a game issue. But I am working around the issues.

**Comment by parkervcp** [comment]
This has been resolved on https://github.com/parkervcp/eggs/commit/59cb02fa7e171ed7601eb8f65902ca346e428420
